eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
      
spring:  application:    name: CLOUD-GATEWAY
          
  cloud:
    gateway:
      routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
        - Path=/employee/**
        filters:
         - name: CircuitBreaker
           args:
              name: hcm-service
              fallbackuri: forward:/hcmFallBack  
        
      - id: hcm-service
        uri: lb://HCM-SERVICE
        predicates:
        - Path=/hcm/**
        filters:
         - name: CircuitBreaker
           args:
              name: hcm-service
              fallbackuri: forward:/hcmFallBack
        
      - id: promotion-service
        uri: lb://PROMOTION-SERVICE
        predicates:
        - Path=/promotion/** 
        filters:
         - name: CircuitBreaker
           args:
              name: promotion-service
              fallbackuri: forward:/promotionFallBack  
        
server:
  port: 9194    
  
  
management:
   endpoints:
    web:
      exposure:
        include: "*"
        

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000         